package arthur.dy.lee.model;

import java.io.Serializable;

public class DatabaseSource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.id
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.name
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.url
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.username
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.password
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.driver_class_name
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String driverClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.type
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column database_source.comment
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.id
     *
     * @return the value of database_source.id
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.id
     *
     * @param id the value for database_source.id
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.name
     *
     * @return the value of database_source.name
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.name
     *
     * @param name the value for database_source.name
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.url
     *
     * @return the value of database_source.url
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.url
     *
     * @param url the value for database_source.url
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.username
     *
     * @return the value of database_source.username
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.username
     *
     * @param username the value for database_source.username
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.password
     *
     * @return the value of database_source.password
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.password
     *
     * @param password the value for database_source.password
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.driver_class_name
     *
     * @return the value of database_source.driver_class_name
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getDriverClassName() {
        return driverClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.driver_class_name
     *
     * @param driverClassName the value for database_source.driver_class_name
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setDriverClassName(String driverClassName) {
        this.driverClassName = driverClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.type
     *
     * @return the value of database_source.type
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.type
     *
     * @param type the value for database_source.type
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column database_source.comment
     *
     * @return the value of database_source.comment
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column database_source.comment
     *
     * @param comment the value for database_source.comment
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", driverClassName=").append(driverClassName);
        sb.append(", type=").append(type);
        sb.append(", comment=").append(comment);
        sb.append("]");
        return sb.toString();
    }
}