package arthur.dy.lee.dao;

import arthur.dy.lee.model.DatabaseSource;
import arthur.dy.lee.model.DatabaseSourceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DatabaseSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    long countByExample(DatabaseSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int deleteByExample(DatabaseSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int insert(DatabaseSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int insertSelective(DatabaseSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    List<DatabaseSource> selectByExample(DatabaseSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    DatabaseSource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int updateByExampleSelective(@Param("record") DatabaseSource record, @Param("example") DatabaseSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int updateByExample(@Param("record") DatabaseSource record, @Param("example") DatabaseSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int updateByPrimaryKeySelective(DatabaseSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table database_source
     *
     * @mbg.generated Wed Dec 01 11:23:46 CST 2021
     */
    int updateByPrimaryKey(DatabaseSource record);
}