app:
  id: Uhw7L2bcQAGkHmc1KDuldl1OMm64n2q6


redis:
  host: 127.0.0.1
  port: 6379
  password: 123456a?


spring:
  application:
    name: springboot
  redis:
    host: 127.0.0.1
    port: 6379
    passsword: 123456a?
  datasource:
    default:
      username: lee
      password: eee
      url: jdbc:mysql://localhost:3306/lee?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      openMulti: true
      type: com.zaxxer.hikari.HikariDataSource
      idle-timeout: 30000
    multi:
      - key: test1
        password: eee
        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
        idle-timeout: 20000
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        username: lee

#mybatis-plus:
#  mapper-locations: classpath*:mapping/*Mapper.xml