
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.test.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&usessl=false&servertimezone=GMT%2B8
spring.datasource.test.username=lee
spring.datasource.test.password=eee
spring.datasource.test.driver-class-name=com.mysql.cj.jdbc.Driver